env:
  browser: true

extends: airbnb

settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'

rules:
  import/no-unresolved: 'off'
  no-console: 'error'
  react/sort-comp: 'off'

parser: babel-eslint

globals:
  jest: false
  it: false
  describe: false
  expect: false
  beforeAll: false
  afterAll: false
